spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: zhdv271@gmail.com
    password: qmshucjeheijjicr
    properties:
      mail:
        smtp:
          starttls:
                  enable: true
          auth: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  flyway:
    enabled: true
    ignore-missing-migrations: true
    locations: classpath:/migration
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/postgres"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/postgres"
    driver-class-name: org.postgresql.Driver


server:
  port: 8080

security:
  secretKey: top_secret_key_hoho!

jwtconfig:
  secret: secret
  expiration: 6000000

amazon:
    serverUrl: "https://jd2aws.s3.eu-central-1.amazonaws.com"
    awsAccessKeyId: AKIASI44GPTY5A5IU7EZ
    awsSecretKey: 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
    folder: user
    bucket: jd2aws
    region: eu-central-1
