spring:
  profiles:
    include: default
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/postgres"
      maximum-pool-size: 10
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/postgres"

jwtconfig:
  secret: secret
  expiration: 600